apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes for a simple WAS Liberty app
name: liberty-starter
version: 0.1.0
maintainers:
  - name: David Carew
    email: carew@us.ibm.com
